listings: true
number-sections: true
table-of-contents: true
template: eisvogel
variables:
  linkcolor: blue
  table-use-row-colors: true
  titlepage: true
  toc-own-page: true
  toc-title: Beispiel PDF
