name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'examples/**'
  release:
    types:
      - published
  pull_request:
    paths-ignore:
      - '**.md'
      - 'examples/**'

env:
  IMAGE_BASE_NAME: vergissberlin/pandoc-eisvogel-de

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Define environment variables
        env:
          LATEST_TAG: '${{ env.IMAGE_BASE_NAME }}:latest'
          PLANTUML_TAG: '${{ env.IMAGE_BASE_NAME }}:plantuml'
        run: |
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
          echo "PLANTUML_TAG=${PLANTUML_TAG}" >> $GITHUB_ENV

      - name: Build base image
        run: docker build -t "${LATEST_TAG}" .

      - name: Run base image
        run: |
          cd examples/basics
          docker run --rm -v $(pwd):/data "${LATEST_TAG}" -d config.yaml -o doc.pdf doc.md

      - name: Build plantuml image
        run: |
          cd plantuml
          docker build -t "${PLANTUML_TAG}" .

      - name: Run plantuml image
        run: |
          cd examples/plantuml
          docker run --rm -v $(pwd):/data "${PLANTUML_TAG}" -o doc.pdf doc.md

  # Publish the image to GitHub Container Registry
  # https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_BASE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_BASE_NAME }}:plantuml
