name: Create Draft Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        env:
          TAG_REF: ${{ github.ref }}
        run: |
          TAG_NAME=$(echo "${TAG_REF#refs/tags/}")
          echo "VERSION::${TAG_NAME#v}" >> $GITHUB_ENV

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this release
            - Update [pandoc/latex](https://hub.docker.com/r/pandoc/latex) (base image) to ${{ env.VERSION }}

            Images:
            - `vergissberlin/pandoc-eisvogel-de:${{ env.VERSION }}`
            - `vergissberlin/pandoc-eisvogel-de:${{ env.VERSION }}-plantuml`
          draft: true
